language: python

python:
  - 2.7
  - 3.3

env:
  - DJANGO=1.5.7
  - DJANGO=1.6.4

install:
  - pip install -q Django==$DJANGO
  - pip install pyquery
  - python setup.py -q install
  - npm install -g grunt-cli
  - pushd . ; cd client && npm install; popd

branches:
  only:
    - master
    - rmi

matrix:
  exclude:
  - python: 3.3
    env: DJANGO=1.5.7

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
 - pushd . ; cd examples && ./manage.py test server; popd
 - pushd . ; cd client && grunt travis-ci; popd
