dist: xenial

services:
  - xvfb

language: python

python:
  - 2.7
  - 3.6
  - 3.7

env:
  - DJANGOVER=django110
  - DJANGOVER=django111
  - DJANGOVER=django20
  - DJANGOVER=django21
  - DJANGOVER=django22

install:
  - pip install tox

matrix:
  exclude:
    - python: 2.7
      env: DJANGOVER=django20
    - python: 2.7
      env: DJANGOVER=django21
    - python: 2.7
      env: DJANGOVER=django22

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sleep 3 # give xvfb some time to start

script:
  - export TOX_ENV=py${TRAVIS_PYTHON_VERSION/./}-${DJANGOVER}
  - tox -r -e "$TOX_ENV"
