language: python

python:
  - 2.7

env:
  - DJANGO=1.5.5 TEST=server
  - DJANGO=1.6.2 TEST=server.tests

install:
  - pip install -q Django==$DJANGO
  - pip install pyquery
  - python setup.py -q install
  - npm install -g grunt-cli
  - cd client && npm install

branches:
  only:
    - master

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
 - cd examples && ./manage.py test $TEST
 - cd client && grunt travis-ci

