language: python

python:
  - 2.7
  - 3.4
  - 3.5

env:
  - DJANGOVER=django17
  - DJANGOVER=django18
  - DJANGOVER=django19

matrix:
  exclude:
    - python: 3.5
      env: DJANGOVER=django17

install:
  - pip install tox

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - export TOX_ENV=py${TRAVIS_PYTHON_VERSION/./}-${DJANGOVER}
  - tox -r -e "$TOX_ENV"
