language: python node_js

python:
  - "2.7"

node_js:
  - 0.8

install:
  - pip install -r requirements.txt --use-mirrors
  - python setup.py -q install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g grunt-cli

script: cd tests && ./manage.py test djangular
