language: python

python:
  - 2.7

env:
  - DJANGO=1.4.5
  - DJANGO=1.5.1

install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install pyquery --use-mirrors
  - python setup.py -q install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g grunt-cli
  - npm install grunt grunt-contrib-jshint grunt-contrib-concat grunt-contrib-uglify karma
  - wget -P tests/lib/angular/ http://ajax.googleapis.com/ajax/libs/angularjs/1.1.5/angular.js

script:
 - cd tests && ./manage.py test server
 - grunt travis-ci
