language: python

python:
  - 2.7
  - 3.3

env:
  - DJANGO=1.5.5 TEST=server
  - DJANGO=1.6.2 TEST=server.tests

install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install pyquery --use-mirrors
  - python setup.py -q install

matrix:
  exclude:
  - python: 3.3
    env: DJANGO=1.5.5 TEST=server

branches:
  only:
    - master

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
 - cd examples && ./manage.py test $TEST
